import type { MetricValue } from '../types/media.types.js';

export function safeDivide(numerator: number, denominator: number): number | null {
  if (!Number.isFinite(numerator) || !Number.isFinite(denominator) || denominator === 0) return null;
  const result = numerator / denominator;
  return Number.isFinite(result) ? result : null;
}

export interface MediaTotals {
  googleSpend: number;
  metaSpend: number;
  googleClaims: number;
  metaClaims: number;
  sitePurchases: number;
  siteRevenue: number;
  itemsViewed: number;
  itemsAddedToCart: number;
  paidImpressions: number | null;
  paidClicks: number | null;
  googleImpressions: number;
  googleInteractions: number;
  metaImpressions: number;
  metaClicks: number;
}

export function calculateMetrics(totals: MediaTotals) {
  const totalSpend = totals.googleSpend + totals.metaSpend;
  const platformClaims = totals.googleClaims + totals.metaClaims;
  const siteAov = safeDivide(totals.siteRevenue, totals.sitePurchases);
  const platformClaimedCac = safeDivide(totalSpend, platformClaims);
  const paidImpressions = totals.paidImpressions;
  const paidClicks = totals.paidClicks;
  const directionalReturnValue = safeDivide(totals.siteRevenue, totalSpend);
  const cacAovRatioValue = platformClaimedCac !== null && siteAov !== null ? safeDivide(platformClaimedCac, siteAov) : null;
  const blendedCtrValue = paidClicks !== null && paidImpressions !== null ? safeDivide(paidClicks, paidImpressions) : null;
  return {
    totalSpend,
    platformClaims,
    referenceMediaScore: null,
    scoreLabel: 'Unscored — baselines pending',
    claimsDifference: platformClaims - totals.sitePurchases,
    directionalReturn: metric(
      directionalReturnValue,
      'DIRECTIONAL',
      'Site revenue / advertising spend',
      'Directional only. Site revenue is not proven to be exclusively generated by paid advertising.',
    ),
    platformClaimedCac: metric(
      platformClaimedCac,
      'PLATFORM_CLAIMED',
      'Advertising spend / platform-claimed conversions',
      'This is not verified new-customer CAC.',
    ),
    claimsVsSite: metric(
      safeDivide(platformClaims, totals.sitePurchases),
      'DERIVED',
      'Platform claims / site purchases',
      'A diagnostic comparison. Platform claims are not verified orders.',
    ),
    siteAov: metric(
      siteAov,
      'VERIFIED',
      'Site revenue / site purchases',
      'Calculated from reconciled site purchase and revenue data.',
    ),
    cacAovRatio: metric(
      cacAovRatioValue,
      'DIRECTIONAL',
      'Platform-claimed CAC / site AOV',
      'Diagnostic only because the numerator uses platform claims.',
    ),
    blendedCtr: metric(
      blendedCtrValue,
      'DERIVED',
      'Sum of raw paid clicks / sum of their matching raw paid impressions',
      'Uses only source rows with a compatible Clicks field and matching impressions. Google Interactions are excluded because the source does not establish that they are Clicks.',
    ),
    paidImpressions,
    paidTrafficActions: paidClicks,
    viewToCartRate: safeDivide(totals.itemsAddedToCart, totals.itemsViewed),
    cartToPurchaseRate: safeDivide(totals.sitePurchases, totals.itemsAddedToCart),
    viewToPurchaseRate: safeDivide(totals.sitePurchases, totals.itemsViewed),
  };
}

function metric(value: number | null, status: MetricValue['status'], formula: string, definition: string): MetricValue {
  return { value, status, formula, definition };
}
