import type { MetricValue } from '../types/media.types.js';

export function safeDivide(numerator: number, denominator: number): number | null {
  if (!Number.isFinite(numerator) || !Number.isFinite(denominator) || denominator === 0) return null;
  const result = numerator / denominator;
  return Number.isFinite(result) ? result : null;
}

export function benchmarkScore(value: number | null, bad: number, good: number): number | null {
  if (value === null || !Number.isFinite(value) || bad === good) return null;
  const score = ((value - bad) / (good - bad)) * 100;
  return Math.max(2, Math.min(100, Math.round(score)));
}

export function weightedBenchmarkScore(items: { score: number | null; weight: number }[]): number | null {
  const available = items.filter((item): item is { score: number; weight: number } => item.score !== null && item.weight > 0);
  const totalWeight = available.reduce((total, item) => total + item.weight, 0);
  if (totalWeight === 0) return null;
  const weightedTotal = available.reduce((total, item) => total + item.score * item.weight, 0);
  return Math.round(weightedTotal / totalWeight);
}

export interface MediaTotals {
  googleSpend: number;
  metaSpend: number;
  googleClaims: number;
  metaClaims: number;
  sitePurchases: number;
  siteRevenue: number;
  itemsViewed: number;
  itemsAddedToCart: number;
  googleImpressions: number;
  googleInteractions: number;
  metaImpressions: number;
  metaClicks: number;
}

export function calculateMetrics(totals: MediaTotals) {
  const totalSpend = totals.googleSpend + totals.metaSpend;
  const platformClaims = totals.googleClaims + totals.metaClaims;
  const siteAov = safeDivide(totals.siteRevenue, totals.sitePurchases);
  const platformClaimedCac = safeDivide(totalSpend, platformClaims);
  const paidImpressions = totals.googleImpressions + totals.metaImpressions;
  const paidTrafficActions = totals.googleInteractions + totals.metaClicks;
  const directionalReturnValue = safeDivide(totals.siteRevenue, totalSpend);
  const cacAovRatioValue = platformClaimedCac !== null && siteAov !== null ? safeDivide(platformClaimedCac, siteAov) : null;
  const blendedCtrValue = safeDivide(paidTrafficActions, paidImpressions);
  const directionalReturnScore = benchmarkScore(directionalReturnValue, 1, 4);
  const cacAovScore = benchmarkScore(cacAovRatioValue, 1, 0.3);
  const blendedCtrScore = benchmarkScore(blendedCtrValue, 0.005, 0.02);
  return {
    totalSpend,
    platformClaims,
    referenceMediaScore: weightedBenchmarkScore([
      { score: directionalReturnScore, weight: 40 },
      { score: cacAovScore, weight: 30 },
      { score: blendedCtrScore, weight: 30 },
    ]),
    claimsDifference: platformClaims - totals.sitePurchases,
    directionalReturn: metric(
      directionalReturnValue,
      'DIRECTIONAL',
      'Site revenue / advertising spend',
      'Directional only. Site revenue is not proven to be exclusively generated by paid advertising.',
      directionalReturnScore,
    ),
    platformClaimedCac: metric(
      platformClaimedCac,
      'PLATFORM_CLAIMED',
      'Advertising spend / platform-claimed conversions',
      'This is not verified new-customer CAC.',
    ),
    claimsVsSite: metric(
      safeDivide(platformClaims, totals.sitePurchases),
      'DERIVED',
      'Platform claims / site purchases',
      'A diagnostic comparison. Platform claims are not verified orders.',
    ),
    siteAov: metric(
      siteAov,
      'VERIFIED',
      'Site revenue / site purchases',
      'Calculated from reconciled site purchase and revenue data.',
    ),
    cacAovRatio: metric(
      cacAovRatioValue,
      'DIRECTIONAL',
      'Platform-claimed CAC / site AOV',
      'Diagnostic only because the numerator uses platform claims.',
      cacAovScore,
    ),
    blendedCtr: metric(
      blendedCtrValue,
      'DERIVED',
      '(Google interactions + Meta link clicks) / paid impressions',
      'A blended response rate. Google supplies interactions while Meta supplies link clicks, so the numerator is not a uniform click definition.',
      blendedCtrScore,
    ),
    paidImpressions,
    paidTrafficActions,
    viewToCartRate: safeDivide(totals.itemsAddedToCart, totals.itemsViewed),
    cartToPurchaseRate: safeDivide(totals.sitePurchases, totals.itemsAddedToCart),
    viewToPurchaseRate: safeDivide(totals.sitePurchases, totals.itemsViewed),
  };
}

function metric(value: number | null, status: MetricValue['status'], formula: string, definition: string, score?: number | null): MetricValue {
  return { value, status, formula, definition, ...(score !== undefined ? { benchmarkScore: score } : {}) };
}
